language: node_js
node_js:
  - "8"
cache: yarn
dist: trusty
addons:
  chrome: stable
before_deploy: "yarn build"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "xsKv0MqHKszkv4t5qkVVt1Ag0Oj8MVxPXPNx1oadW7bE/Fudw9+tpDyG8UlZMvINvllqbS7KwvAH391xiyMz8BJXn/DuzC40C+8GX2RJ1F2WXhMc6ZZY5jNGIoI/ZG0aoc9LXdedM8LrEt3yD4A1aUi2+2l8q3MtqkXnbOKOHfUXuOkyapx1La50SY9PAXyOUDwdrBFZLGjxyb3/nWiBsrMJ6N7mwk3Bxp4vA3IcBlDRx3h7GKfUh36ruyEUZVSdb+fQNnsra/vNjavlwgwFFOD5XC2NDasMvpRf1lLzR/Wc8JbkvnjiSYiMw0uIDCr4C+PRbvMAMJ8DyGTqBypyxzJTksi6+d71mrq+B8M0Rh9Dq3ybonZjyJofc06rfr5qA77djCT0h64kiqypYlXJMfp6jxLQrVYIVZUBe+jtR6hx3zCgbuo7dsF8AX2DttzvyDXGVlNAybqk8Bb8JEkPaWKBiAgHxEA1FIgDJwSPY1V1h4Vr5X6vNYQZLC8EsTQCmc1aYFAbcDduET+msEGg83JLo/YTz4eh8z+LZFZ06E/PByqBHvTWyW68uq8AQ7BO1e1CT6KkG2lQzyVQB+EYKpx2YDG0mq7pDtrN8iCqwxyQgqRHXaHI2xL71ujnj35TTdS6f+gTKm+8BCCFOLE2hwcHBQ7c7Y7XEVCzRgFqFn4="
