// flow-typed signature: f8e66ac4b4240867ac2144cde1a29d40
// flow-typed version: <<STUB>>/postcss-custom-media_v^5.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-custom-media/index' {
  declare module.exports: $Exports<'postcss-custom-media'>;
}
declare module 'postcss-custom-media/index.js' {
  declare module.exports: $Exports<'postcss-custom-media'>;
}
