// flow-typed signature: 4ed55a6d0ec65f36815bf38a16daa6f0
// flow-typed version: <<STUB>>/postcss-nesting_v^2.3.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nesting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nesting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-nesting/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-nesting/index' {
  declare module.exports: $Exports<'postcss-nesting'>;
}
declare module 'postcss-nesting/index.js' {
  declare module.exports: $Exports<'postcss-nesting'>;
}
declare module 'postcss-nesting/test.js' {
  declare module.exports: $Exports<'postcss-nesting/test'>;
}
